server:
  port: 8082
spring:
  application:
    name: storage-service
  redis:
    host: ${DB_IP}
    port: ${REDIS_PORT}
    password: ${DB_PASSWORD}
  datasource:
    url: jdbc:mysql://${DB_IP}:${CART_DB_PORT}/${CART_DB_SCHEMA}?useSSL=false&serverTimezone=UTC
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

  cloud:
    config:
      import-check:
        enabled: false

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-service:8761/eureka/

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace
    org:
      springframework: INFO
