server:
  port: 8090

spring:
  cloud:
    gateway:
      routes:
        - id: product-service
          uri: http://product-service:8082 # product 서비스의 실제 포트 번호에 맞게 수정하세요.
          predicates:
            - Path=/product-service/**

        - id: order-service
          uri: http://order-service:8083 # order 서비스의 실제 포트 번호에 맞게 수정하세요.
          predicates:
            - Path=/order-service/**

        - id: payment-service
          uri: http://payment-service:8084 # payment 서비스의 실제 포트 번호에 맞게 수정하세요.
          predicates:
            - Path=/payment-services/**

        - id: storage-services
          uri: http://storage-services:8085 # storage 서비스의 실제 포트 번호에 맞게 수정하세요.
          predicates:
            - Path=/storage-services/**
        #        - id: auth-service
        #          uri: http://auth-service:8080 # Change the port number to match your auth service's actual port number.
        #          predicates:
        #            - Path=/auth-service/**
        #
        #        - id: user-service
        #          uri: http://user-service:8081 # Change the port number to match your user service's actual port number.
        #          predicates:
        #            - Path=/user-service/**
