server:
  port: 8081

spring:
  application:
    name: payment-service

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
      dialect: org.hibernate.dialect.MySQL8InnoDBDialect

  kafka:
    producer:
      bootstrap-servers: 3.38.228.196:9092
      acks: all
    consumer:
      bootstrap-servers: 3.38.228.196:9092
      group-id: payment-service-group
    listener:
      type: SINGLE


  profiles:
    active:
      - develop
    group:
      develop: "env"


logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace
    org:
      springframework: INFO


kakaopay:
  cid: "TC0ONETIME"
  approval_url: "https://lot-fresh.shop/order/payments/kakaopay/approve"
  fail_url: "https://lot-fresh.shop/order/payments/kakaopay/fail"
  cancel_url: "https://lot-fresh.shop/order/payments/kakaopay/cancel"
  admin_key: "8f2de5fceef170ccd187a4e94c813657"

