server:
  port: 8085

spring:
  application:
    name: payment-service
  datasource:
    url: jdbc:mysql://${DB_IP}:${PAYMENT_DB_PORT}/${PAYMENT_DB_SCHEMA}?serverTimeZone=UTC
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
      dialect: org.hibernate.dialect.MySQL8InnoDBDialect
  profiles:
    active:
      - develop
    group:
      develop: "env"

  redis:
    host: ${DB_IP}
    port: ${REDIS_PORT}
    password: ${DB_PASSWORD}

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-service:8761/eureka/

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace
    org:
      springframework: INFO
