server:
  port: 8081
spring:
  datasource:
    url: ${"USER_DB_URL"}
    username: ${"USER_USERNAME"}
    password: ${"USER_PASSWORD"}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  cloud:
    config:
      import-check:
        enabled: false

