spring:
  application:
    name: order-service
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      dialect: org.hibernate.dialect.MySQL8InnoDBDialect
  # profiles:
  #   active:
  #     - ${PROFILE:local}
  #   group:
  #     develop: "env"
  #     local: "local"

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-service:8761/eureka
