/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BannerItem: typeof import('./src/components/banner/BannerItem.vue')['default']
    BannerSlide: typeof import('./src/components/banner/BannerSlide.vue')['default']
    BestProductList: typeof import('./src/components/product/BestProductList.vue')['default']
    BestProductListSlide: typeof import('./src/components/product/BestProductListSlide.vue')['default']
    CancelRefundAmountInfo: typeof import('./src/components/mypage/cancelrefund_detail/CancelRefundAmountInfo.vue')['default']
    CancelRefundDateInfo: typeof import('./src/components/mypage/cancelrefund_detail/CancelRefundDateInfo.vue')['default']
    CancelRefundHeader: typeof import('./src/components/mypage/cancelrefund_detail/CancelRefundHeader.vue')['default']
    CancelRefundItem: typeof import('./src/components/mypage/cancelrefund_list/CancelRefundItem.vue')['default']
    CancelRefundItemInfo: typeof import('./src/components/mypage/cancelrefund_detail/CancelRefundItemInfo.vue')['default']
    CancelRefundItemList: typeof import('./src/components/mypage/cancelrefund_list/CancelRefundItemList.vue')['default']
    CategoryProductList: typeof import('./src/components/product/CategoryProductList.vue')['default']
    DeliveryInfo: typeof import('./src/components/order/orderSheet/DeliveryInfo.vue')['default']
    ElCollapse: typeof import('element-plus/es')['ElCollapse']
    ElCollapseItem: typeof import('element-plus/es')['ElCollapseItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    Footer: typeof import('./src/components/common/Footer.vue')['default']
    Header: typeof import('./src/components/common/Header.vue')['default']
    Menu: typeof import('./src/components/common/Menu.vue')['default']
    NewProductList: typeof import('./src/components/product/NewProductList.vue')['default']
    NewProductListSlide: typeof import('./src/components/product/NewProductListSlide.vue')['default']
    Order: typeof import('./src/components/order/Order.vue')['default']
    OrderDetail: typeof import('./src/components/order/OrderDetail.vue')['default']
    OrdererInfo: typeof import('./src/components/order/orderSheet/OrdererInfo.vue')['default']
    OrderProduct: typeof import('./src/components/order/orderSheet/OrderProduct.vue')['default']
    Payment: typeof import('./src/components/order/orderSheet/Payment.vue')['default']
    PaymentAmount: typeof import('./src/components/order/orderSheet/PaymentAmount.vue')['default']
    PaymentBill: typeof import('./src/components/order/orderSheet/PaymentBill.vue')['default']
    PaymentInfo: typeof import('./src/components/order/orderDetail/PaymentInfo.vue')['default']
    ProductDeliveryInfo: typeof import('./src/components/order/orderDetail/ProductDeliveryInfo.vue')['default']
    ProductDetail: typeof import('./src/components/product/item/ProductDetail.vue')['default']
    ProductDetailImage: typeof import('./src/components/product/item/ProductDetailImage.vue')['default']
    ProductItem: typeof import('./src/components/product/item/ProductItem.vue')['default']
    ProductThumbnail: typeof import('./src/components/product/item/ProductThumbnail.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SalesProductList: typeof import('./src/components/product/SalesProductList.vue')['default']
  }
}
