server:
  port: 8083

spring:
  application:
    name: product-service
  datasource:
    url: jdbc:mysql://${DB_IP}:${PRODUCT_DB_PORT}/${PRODUCT_DB_SCHEMA}?serverTimeZone=UTC
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      dialect: org.hibernate.dialect.MySQL8InnoDBDialect

  redis:
    host: ${DB_IP}
    port: ${REDIS_PORT}
    password: ${DB_PASSWORD}

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-service:8761/eureka/

logging:
  level:
    org.hibernate.SQL: warn
    org:
      springframework:
