server:
  port: 8083

spring:
  application:
    name: product-service

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
      dialect: org.hibernate.dialect.MySQL8InnoDBDialect
  # profiles:
  #   active:
  #     - ${PROFILE:local}
  #   group:
  #     develop: "env"
  #     local: "local"

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-service:8761/eureka/

logging:
  level:
    org.hibernate.SQL: debug
    org:
      springframework:
